### ISSUE TITLE
remove the field ID from all dashboards

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#117]
Currently, some list pages have the field ID from. Example:  `users` , `questions` 

![image](https://user-images.githubusercontent.com/6463001/117538437-dab11080-b00e-11eb-83a7-9c8df2930e01.png)

![image](https://user-images.githubusercontent.com/6463001/117538481-0b914580-b00f-11eb-8b4a-619e7ed7a27a.png)

**Comment by andre-dan** [comment]
my english is beginer
