### ISSUE TITLE
Improve class_diagram, add support to answering survey

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#154]
Should support the same user answering the same survey multiple times.

**Comment by ValmirJuniorr** [comment]
I would like to help with this issue, (:

**Comment by garciajordy** [comment]
![Entity Relationship Diagram (1)](https://user-images.githubusercontent.com/74253475/119021155-beff2000-b9a7-11eb-8faa-4efb5f7a3cb8.png)
