### ISSUE TITLE
Only add "ready to be answered" or add a flag to control the questions on the survey

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#205]
Question
add column `ready_to_be_answered` to question
add validation to `ready_to_be_answered` that validates if there is at least one valid option for that question

Option
add validation to `option`  that checks if `question` has correct options when question has `ready_to_be_answered`

**Comment by garciajordy** [comment]
Create method on survey that checks if all questions that belongs to that survey have at least one correct option
