### ISSUE TITLE
Go to the `Survey question page` from `List Surveys page` 

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#256]
On [List Surveys page](https://espoolingo.herokuapp.com/surveys), the user can see all surveys that are ready to be answered.

Atm, if the user clicks on the survey card, it will create an AnswerSurvey. After that it should be redirected to the Survey and see the first question to be answered.
![image](https://user-images.githubusercontent.com/6463001/143671038-501463a1-dbfb-490d-91ed-51315240e61e.png)

**Comment by edimossilva** [comment]
@iurynogueira and @mizek1, I think we should prioritize this issue over others because:

- it helps us to go through the happy path. 
- it requires more backend integration and it is a good way to confirm if the backend is providing correct data.

 What do you guys think about it?

**Comment by iurynogueira** [comment]
Sure, we can priorize this to have we a MVP fast possible.
