### ISSUE TITLE
Fix docker ENV bug and add instructions for people who want to use DOCKER

### ISSUE THREAD

**Issue by garciajordy** [espoo-dev/espoo-dev#319]
The problem now is that we have a check if `ENV["DOCKER_ENV"]` is set to true, while the ENV variables are not able to return a boolean. Instead, it is sending back the string `"true"` or `"false"`. 

Maybe we could add a check to compare it with the string `"true"`, which could solve this issue.

If we add this check, we should also add some instructions in the documentation for other users who want to use DOCKER.

**Comment by garciajordy** [comment]
HUB_URL is only activated when adding any URL to the `ENV["HUB_URL"]`.
![image](https://user-images.githubusercontent.com/74253475/135032838-08d838ec-69c2-4ff7-9590-69bdfb646517.png)

**Comment by edimossilva** [comment]
Agreed, my bad!
