### ISSUE TITLE
import helper for specs properly

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#325]
find a proper way of [include helper](https://github.com/espoo-dev/espoo-dev/blob/e2f30cebf3e657bcbc3174186592edb0cd5ac659/backend/spec/rails_helper.rb#L73)

**Comment by garciajordy** [comment]
Isn't it already there?? 
![image](https://user-images.githubusercontent.com/74253475/135907882-6b1a1ea0-d4fc-40c3-94db-77ac208f8d79.png)

**Comment by edimossilva** [comment]
@garciajordy nope, for the line that I linked  we have to disable rubocop. There is a better way of doing that
