### ISSUE TITLE
Show answered questions count at survey card

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#335]
At surveys page(https://espoo.herokuapp.com/surveys), currently is possible to see info for each survey card like :
-Name
-Description
-Total questions quantity

Add the info "answered questions quantity" to the survey card.

Obs: Need to think well about how to approach this, @garciajordy I want you do do it without my help. You can discuss this with @leonardobrito if he shows up, but don't depend on him, he usually takes some time to answer and I don't want you to get blocked by him.

**Comment by leonardobrito** [comment]
I'm here ✋🏻 
If you want to discuss anything @garciajordy, just tag me here or on slack. 😃

**Comment by garciajordy** [comment]
Could you provide me with a better description of the missing attributes...

for example:
- answered = boolean that checks whether there is already an answer_survey.
- The other two I'm not sure about, do you need the quantity of the answers or do you need the answers as well? and quantity of questions or... ?
-

**Comment by edimossilva** [comment]
> Could you provide me with a better description of the missing attributes...
> 
> for example:
> - answered = boolean that checks whether there is already an answer_survey.
> - The other two I'm not sure about, do you need the quantity of the answers or do you need the answers as well? and quantity of questions or... ?
> 

"Answered questions quantity" is only one number. 

For example Survey A has q1, q2,q3

The user partialy answers survey A with q1 and q2. These 2 anwers are stored in an answersurvey.

"Answered questions quantity"=2

Does this make sense? Any questions?

**Comment by edimossilva** [comment]
Yes, 

if user1 hás only one answer for that survey, he should see 1 answer for that survey.

if user2 hás 2 answers for that survey, he should see 2 answer for that survey
