### ISSUE TITLE
Use bootstrap 5

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#339]
Upgrade bootstrap version on rails app

**Comment by maniSHarma7575** [comment]
@edimossilva Can I work on this issue?

**Comment by edimossilva** [comment]
Sure @maniSHarma7575, go for it!

**Comment by edimossilva** [comment]
> @edimossilva Can I work on this issue?

@maniSHarma7575 , are you having any trouble with this issue? Can I help?
