### ISSUE TITLE
Parse/convert  "html page" to "slim page"

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#355]
- Parse page [raw design/ogin.html](https://github.com/espoo-dev/espoo-dev/blob/main/raw%20design/login.html) to [backend/app/views/devise/new.slim](https://github.com/espoo-dev/espoo-dev/blob/main/backend/app/views/devise/sessions/new.slim)

- While parsing, consider also the files  [raw design/style.css](https://github.com/espoo-dev/espoo-dev/blob/main/raw%20design/style.css) and [raw design/logo2.png](https://github.com/espoo-dev/espoo-dev/blob/main/raw%20design/logo2.png)

 
- While parsing, rename logo2.png to logo.png

**Comment by nikhilbhatt** [comment]
I want to work on this issue.
