### ISSUE TITLE
Fix SignUp page (add checkbox to role) 

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#368]
How to reproduce?
1. Visit https://espoo.herokuapp.com/users/sign_up
2. Fill up Email, password and confirm the password
3. Click `sign_up` button
4. **Should create a user, but at the moment raise an error due to `missing role attribute`**
![image](https://user-images.githubusercontent.com/6463001/137594550-4a6eca65-83c8-41db-a339-8ab437dbb6e1.png)

note 1: use a checkbox for selecting available roles.
note 2: should be able to select all roles except `admin role`
note 3: no need to worry about layout

**Comment by adithyanandakumar** [comment]
@edimossilva I would love to work on this, but can I ask which are the other roles to be added?

**Comment by edimossilva** [comment]
> @edimossilva  That's gr8! Be aware that I only know basic HTML, css and a bit of Js...

This issue was closed by https://github.com/espoo-dev/espoo-dev/pull/374

@adithyanandakumar maybe you could work on https://github.com/espoo-dev/espoo-dev/issues/376, any thoughts?
