### ISSUE TITLE
Refactor style for bg-image class

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#372]
- Apply [BEM](http://getbem.com/introduction/) for [bg-image](https://github.com/espoo-dev/espoo-dev/blob/f9cb84922e9bedb4ac05375961e14e34c766a64b/backend/app/assets/stylesheets/application.scss#L11)
- Extract bg-image to other scss file

**Comment by aqsaaqeel** [comment]
I'm very new to open source so i need your help to understand where exactly I need to apply the BEM
