### ISSUE TITLE
Handle error messages

### ISSUE THREAD

**Issue by iurynogueira** [espoo-dev/espoo-dev#396]
When starting a survey I verified that a technical error is returned to the user, it is necessary to change it to the message returned from the back.

**Comment by edimossilva** [comment]
@garciajordy , could you please check this?

**Comment by edimossilva** [comment]
> When starting a survey I verified that a technical error is returned to the user, it is necessary to change it to the message returned from the back.

@iurynogueira , please improve the title and issue description.
note: take this as an exercise to improve your skills.
