### ISSUE TITLE
Add RoR reference projects to backend/readme.md

### ISSUE THREAD

**Issue by philipeleandro** [espoo-dev/espoo-dev#411]
To help with any questions, these projects have been developed in ruby on rails and they will be used as references:

• Chatwoot: https://www.chatwoot.com/
• Repository: https://github.com/chatwoot/chatwoot

• Dev.to: https://dev.to/
• Repository: https://github.com/forem/forem

• Gitlab: https://about.gitlab.com/
• Repository: https://github.com/gitlabhq/gitlabhq

Note: If you find some project that can be used as reference too, you can add.

**Comment by edimossilva** [comment]
I would suggest renaming the issue to `Add RoR reference projects to backend/readme.md`

**Comment by philipeleandro** [comment]
right, the issue name was edited to `Add RoR reference projects to backend/readme.md`.
