### ISSUE TITLE
Remove result of answers in questions list

### ISSUE THREAD

**Issue by iurynogueira** [espoo-dev/espoo-dev#416]
The url `https://espoo.herokuapp.com/api/v1/surveys` return a list questions with the possibles options however i see this like a problem because the user can debug the network and see the answers corrects, i belive that the correct is not show this information.

`"options": [
          {
            "id": 767,
            "name": "Option 1",
            "correct": true
          },
          {
            "id": 768,
            "name": "Option 2",
            "correct": false
          }
 ]`

**Comment by edimossilva** [comment]
@iurynogueira , I completely agree, we need to rethink a few things about design/structure, we will have a meeting this weekend

**Comment by PolinaStamenova** [comment]
Can I work on this task?
