### ISSUE TITLE
Answered questions quantity not working properly

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#442]
The seed file creates 2 `answered questions` for Animals survey - Teacher.

When visiting http://localhost:3000/surveys, `questions answered` for `Animals survey - Teacher` should be equals to 2, but it is equal to 1.

**Comment by PolinaStamenova** [comment]
@edimossilva 

for me it shows `2 questions answered.`
![image](https://user-images.githubusercontent.com/79217155/149491377-f135bf5a-0ffe-4de4-8f66-2e4ef0801438.png)

**Comment by edimossilva** [comment]
@PolinaStamenova , I fixed this in another PR  but didn't realise. Thanks for noticing
