### ISSUE TITLE
List Surveys

### ISSUE THREAD

**Issue by amiapmorais** [espoo-dev/espoo-dev#450]
List surveys so student can choose which one to respond

**Comment by edimossilva** [comment]
@amiapmorais , usually people go with `to answer` instead of `to respond`

**Comment by amiapmorais** [comment]
I thought better option was `to respond` a survey, and `to answer` a question. But, can I always use `to answer` then?

**Comment by edimossilva** [comment]
Humm, now you got me, I really don't know
