### ISSUE TITLE
Add missing Internalization to views 

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#457]
- At [questions/show](https://github.com/espoo-dev/espoo-dev/blob/main/backend/app/views/questions/show.slim) the strings `"This is a #{@question.question_type.name.downcase} question." ` and `Next` have no translations
- At [surveys/index](https://github.com/espoo-dev/espoo-dev/blob/main/backend/app/views/surveys/index.slim) the strings `answered` and `pluralize(survey[:answered_questions_quantity], 'question')` are not translated

**Comment by edimossilva** [comment]
@andre-dan

**Comment by edimossilva** [comment]
@andre-dan will work on this issue, @garciajordy  please assist him if necessary

**Comment by andre-dan** [comment]
ok

**Comment by edimossilva** [comment]
@andre-dan, removing this task from you due to inactivity, please ask me some other when you decide to come back
