### ISSUE TITLE
Remove refresh button from surveys page

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#550]
**User feedback:** clicking it does not changes anything for them

![image](https://user-images.githubusercontent.com/6463001/150860404-6da9ba86-5855-4183-b066-7ff35813e785.png)

**Comment by iurynogueira** [comment]
Fixed! This problem is the loading of surveys list no is sync with the request of refresh. Now by click in refresh button this loading is called and list hidden, when request finalized the list is showing again but now updated. Thanks user ❤️
