### ISSUE TITLE
A survey should have its own page

### ISSUE THREAD

**Issue by andersonmalheiro** [espoo-dev/espoo-dev#599]
Today when selecting a survey to answer, the user is not redirected to a new page. All the logic is done in one page, like requesting the surveys, selecting one and replacing the components, all this done via state changes on React side.

**Expected behavior:** A user access the `/surveys` page and select one survey on the list. Doing this will trigger a redirect to `/surveys/:survey_id`, where the page fetches the survey by its ID and handle the logic. Ending the survey the user sees the summary and can go back to `/surveys` again.

**Comment by edimossilva** [comment]
@iurynogueira and @andersonmalheiro , have you guys discussed how answering survey will take place considering:

- the current way, form listing surveys
- new way, from a group that has many surveys

I believe both ways can be supported
