### ISSUE TITLE
Answering survey crashes when answers order change

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#611]
For some reason is possible for user to answer `question 2` before `question 1`.
Currently, there are 2 arrays for questions, 1 is at the root level and the second one is at curren_answers_survey level.
Frontend client should use questions from `current_answers_survey`.

note:This issue was fixed before, maybe it came back now with the component's refactor. @iurynogueira and @andersonmalheiro , please discuss how to solve this.

note2: I am thinking about removing questions from the root level and only letting questions available at answers_survey, still need to double-check this because maybe it demands some tricky work 

![image](https://user-images.githubusercontent.com/6463001/152863077-6bc0b8d9-c883-4ab5-a1ae-9c6dd0d67e90.png)

**Comment by iurynogueira** [comment]
fixed in #614
