### ISSUE TITLE
Add integration with slack

### ISSUE THREAD

**Issue by ValmirJuniorr** [espoo-dev/espoo-dev#656]
- When a user finishes answering a survey, a notification should be sent to a Slack channel.
E.g. Survey "Simple present" from teacher "Valmir" has been answered now. It has been answered 112 times.

**Comment by ValmirJuniorr** [comment]
Access to the manager apps on slack
 - https://api.slack.com/apps/A035UFJ777C/incoming-webhooks?success=1
 
tutorial, that I am using:
- https://dev.to/ksushiva/sending-slack-notifications-with-ruby-on-rails-57m

**Comment by iurynogueira** [comment]
I put faith now
