### ISSUE TITLE
Runs Slack Notification in a job on sidekiq

### ISSUE THREAD

**Issue by valmirosjunior** [espoo-dev/espoo-dev#660]
For while, the app is runing on heroku, but I think it's necessary to move on the slack notifications to run on a background service using sidekiq.
The integration with slack I has been created on that issue: 
https://github.com/espoo-dev/espoo-dev/issues/656

**Comment by maniSHarma7575** [comment]
@valmirosjunior Can I take this one?

**Comment by valmirosjunior** [comment]
I think yes, but is better to check it up with @edimossilva I thnk yes, but it is better check it up with @edimossilva,

**Comment by valmirosjunior** [comment]
@maniSHarma7575 , I talked with @edimossilva and he to me that you can do it, thanks!

**Comment by maniSHarma7575** [comment]
Ok @valmirosjunior Thanks I am starting on this.

**Comment by maniSHarma7575** [comment]
@valmirosjunior Here is the link to PR: https://github.com/espoo-dev/espoo-dev/pull/798

State: Work in progress.

**Comment by valmirosjunior** [comment]
Nice @maniSHarma7575, just let me know when you finish, so I can review it.
Thanks, good job!

**Comment by maniSHarma7575** [comment]
@valmirosjunior PR is ready for review.

**Comment by valmirosjunior** [comment]
Good job man, I made just a few suggestions.
