### ISSUE TITLE
Use image_url from question object at answering question page

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#698]
While answering a question, an image should be displayed when it exists
![image](https://user-images.githubusercontent.com/6463001/161089100-e5397371-bb2d-40af-9b41-2790bb8a58c3.png)

Now a new optional field `image_url` can be found on the question object.
![image](https://user-images.githubusercontent.com/6463001/161088839-e1e0dd94-c005-4b21-8523-f4b12fcda929.png)

**Comment by mizek1** [comment]
Can I work on this one?

**Comment by edimossilva** [comment]
Sure, please go for it
