### ISSUE TITLE
update database diagram

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#70]

**Comment by garciajordy** [comment]
# Entity Relationship Diagram

**Models:**
- Add the User model (changed role type to integer).
- Add the Question_type model.
- Add the Question model.
- Add the Survey model.

**Associations:**
- User: has_many questions, has_many surveys.
- Question_type: has_many questions.
- Question: belongs_to User, belongs_to Survey, belongs_to Question_type.
- Survey: belongs_to User, has_many questions.


_See the PDF file provided at the bottom._ 😄 


[Entity Relationship Diagram.pdf](https://github.com/espoo-dev/espoo-dev/files/6394006/Entity.Relationship.Diagram.pdf)

**Comment by edimossilva** [comment]
HI @garciajordy , looks nice!

1. can you create the folder "backend/doc"  on the project ?
2. instead of a pdf put an image inside of  "backend/doc"?
3. Can you make Role an isolated table instead of string? Since it is related to issue #51
