### ISSUE TITLE
use image_url from survey object at surveys page

### ISSUE THREAD

**Issue by philipeleandro** [espoo-dev/espoo-dev#705]
The user can register an `image url` when he's creating a new survey. This image_url when it exists, it'll be display a cover photo.
![image](https://user-images.githubusercontent.com/92264330/161426581-ce00de64-aaf5-4685-97fd-90b686c2b88f.png)

Now, survey object has the optional field `image_url`
![image](https://user-images.githubusercontent.com/92264330/161426816-fbd17511-4f20-4962-9ec9-f7bc9d15acfb.png)

The image_url can be found in:
![image](https://user-images.githubusercontent.com/92264330/161427599-f8eeadb5-9fbf-46e7-bb23-cb49a9442a9a.png)

**Comment by mizek1** [comment]
Can I work on this issue?

**Comment by iurynogueira** [comment]
> Can I work on this issue?

Yeah!

![](https://media3.giphy.com/media/ly3tQYHmXMsCI/giphy.gif?cid=ecf05e470z9cgz42d8t7x69hisu2q5zo81yfe7ctz7pyl3bz&rid=giphy.gif&ct=g)
