### ISSUE TITLE
Create "option" entity

### ISSUE THREAD

**Issue by edimossilva** [espoo-dev/espoo-dev#81]
A question can have 0 or many options.
If a question has type equals to SingleOption or MultipleOptions it needs to have answers_options
An option belongs to a question 

example 1:
question: What is the plural of "you"?
question_type: SingleOption
answers_options: option 2
option 1) they
option 2) you
option 3) it
option 4) she

example 2:
question: What are the singular of "they"?
question_type: MultipleOption
answers_options: option 2, option 3, option 4
option 1) we
option 2) he
option 3) it
option 4) she

**Comment by garciajordy** [comment]
I will solve this issue
