### ISSUE TITLE
add filter to list specific roles on register page

### ISSUE THREAD

**Issue by andersonmalheiro** [espoo-dev/espoo-dev#94]
looks like it does not work properly when user is not logged.
Add `it` for scenario when user is nil https://github.com/espoo-dev/espoo-dev/blob/843befedcb6403127d38ef1b7a5a0a6296c0add4/backend/spec/models/role_spec.rb#L56

**Comment by andre-dan** [comment]
.

**Comment by edimossilva** [comment]
Couldn't reproduce. Closing issue

**Comment by edimossilva** [comment]
Added tests related to it in https://github.com/espoo-dev/espoo-dev/pull/317
